agents/api/urls.py
from django.urls import path
from .views import (
    CreateAgentView, ActivateView
)


urlpatterns = [
    path('create-agent/', CreateAgentView.as_view()),
    path('activate/<uidb64>/<token>', ActivateView.as_view()),
]

agents/urls.py
from django.urls import path
from .views import (
    AgentListView, AgentCreateView, AgentDetailView, 
    AgentUpdateView, SupportCreateView, Agent_Delete, activate
)


app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', Agent_Delete, name='agent-delete'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('support/', SupportCreateView.as_view(), name='support-create'),
    
    path('activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.schemas import get_schema_view
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('account.urls')),
    # path('files/', include('filed.urls', namespace="files")),
    # path('agents/',  include('agents.urls', namespace="agents")),

    # path('api_schema/', get_schema_view(
    #     title='API Schema',
    #     description='Guide for the REST API'
    # ), name='api_schema'),

    # path('swagger-ui/', TemplateView.as_view(
    #     template_name='docs.html',
    #     extra_context={'schema_url':'api_schema'}
    #     ), name='swagger-ui'),

    # Api Banger Boos
    path('api/', include("filed.api.urls")),
    path('api/auth/', include("account.api.urls")),
    path('api/agent/', include("agents.api.urls")),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,
document_root=settings.MEDIA_ROOT)

agents/models.py
from django.db import models

# Create your models here.

filed/models.py
from django.db import models
from account.models import UserProfile, User


class FileManager(models.Manager):
    def get_queryset(self):
        # return super().get_queryset()
        return super().get_queryset().filter(is_deleted=False)


class File(models.Model):
    file_name = models.CharField(max_length=500)
    file_date_added = models.DateField(auto_now_add=True)
    headline = models.CharField(max_length=500, null=True, blank=True)
    passport = models.CharField(max_length=500, null=True, blank=True)
    identify_holder = models.CharField(max_length=500,  null=True, blank=True)
    estate_reg = models.CharField(null=True, blank=True, max_length=500)
    phone_number = models.CharField(null=True, blank=True, max_length=500)
    email = models.EmailField(null=True, blank=True)
    value_delineation = models.CharField(null=True, blank=True, max_length=60)
    delineation_date = models.DateField(null=True, blank=True)
    delineation_payment = models.CharField(null=True, blank=True, max_length=40)
    consecutive_delineation = models.CharField(null=True, blank=True, max_length=40)
    visited_by = models.CharField(null=True, blank=True, max_length=70)
    State_type = models.ForeignKey("StateType", null=True, blank=True, on_delete=models.SET_NULL)
    delivery_date = models.DateField(null=True, blank=True)
    notification_date = models.DateField(null=True, blank=True)

    operator_observation = models.TextField(max_length=2000, null=True, blank=True)
    # observation_list = models.ForeignKey("operatorObservation", null=True, blank=True, on_delete=models.SET_NULL)
    
    ref_code = models.CharField(max_length=500, blank=True, null=True)
    completed = models.BooleanField(default=False)

    observation = models.TextField(max_length=1000, null=True, blank=True)
    observation_date = models.DateTimeField(null=True, blank=True)

    review = models.BooleanField(default=False)
    review_date = models.DateTimeField(null=True, blank=True)

    underReview = models.BooleanField(default=False)
    underReview_date = models.DateTimeField(null=True, blank=True)

    is_notified = models.CharField(max_length=500, blank=True, null=True)
    is_notified_date = models.DateTimeField(null=True, blank=True)
    is_notified_observation = models.TextField(max_length=1000, null=True, blank=True)

    correct_document = models.CharField(max_length=500, blank=True, null=True)
    correct_document_date = models.DateTimeField(null=True, blank=True)

    process_act_num = models.CharField(max_length=500, null=True, blank=True)
    process_act_num_date = models.DateTimeField(null=True, blank=True)
    liquidation_value = models.CharField(max_length=500, null=True, blank=True)

    is_personal_notified = models.CharField(max_length=500, blank=True, null=True)
    is_personal_notified_date = models.DateTimeField(null=True, blank=True)
    is_personal_notified_observation = models.TextField(max_length=1000, null=True, blank=True)

    # payment form
    payment = models.BooleanField(default=False)
    payment_status_date = models.DateTimeField(null=True, blank=True)

    payment_receipt_number = models.CharField(max_length=500, null=True, blank=True)
    payment_receipt_date = models.DateTimeField(null=True, blank=True)
    license_value = models.CharField(max_length=500, null=True, blank=True)
    delineation_tax_value = models.CharField(max_length=500, null=True, blank=True)

    payment_receipt_number2 = models.CharField(max_length=500, null=True, blank=True)
    payment_receipt_date2 = models.DateTimeField(null=True, blank=True)
    license_value2 = models.CharField(max_length=500, null=True, blank=True)
    delineation_tax_value2 = models.CharField(max_length=500, null=True, blank=True)

    # GENERATE RESOLUTION
    resolution_number = models.CharField(max_length=500, null=True, blank=True)
    resolution_date = models.DateTimeField(null=True, blank=True)
    resolution_number2 = models.CharField(max_length=500, null=True, blank=True)
    resolution_date2 = models.DateTimeField(null=True, blank=True)
    resolution_notification_date = models.DateTimeField(null=True, blank=True)
    
    official_letter_issued = models.DateField(null=True, blank=True)

    updatedAt = models.DateField(null=True, blank=True)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    file_type = models.ForeignKey("FileType", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category", related_name="files", null=True, blank=True, on_delete=models.SET_NULL)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)
    objects = FileManager()

    def __str__(self):
        return f"{self.file_name}"


class VeriyDoc(models.Model):
    filev = models.ForeignKey("File", related_name="verifyDoc", on_delete=models.CASCADE)

    Copia_de_cedula_del_propietario_pasaporte = models.BooleanField(default=False)
    Certificado_de_tradición_y_libertad = models.BooleanField(default=False)
    Copia_de_la_escritura = models.BooleanField(default=False)
    Paz_y_salvo_municipal = models.BooleanField(default=False)
    Copia_del_impuesto_predial = models.BooleanField(default=False)
    Certificado_catastral = models.BooleanField(default=False)
    Planos_arquitectónicos_y_estructurales = models.BooleanField(default=False)
    Planos_topográficos = models.BooleanField(default=False)
    CD_o_USB = models.BooleanField(default=False)
    Copia_de_la_tarjeta_profesional = models.BooleanField(default=False)
    Formulario_único_nacional = models.BooleanField(default=False)
    Certificado_de_delineación_y_comprobante_de_pago = models.BooleanField(default=False)
    Viabilidad_de_energía_y_acueducto  = models.BooleanField(default=False)
    Viabilidad_de_alcantarillado_y_aseo  = models.BooleanField(default=False)
    Certificado_de_sismo_resistencia  = models.BooleanField(default=False)
    Memorias_de_calculo  = models.BooleanField(default=False)
    Estudio_de_suelos  = models.BooleanField(default=False)
    Peritaje_técnico  = models.BooleanField(default=False)
    Plan_de_majo_ambiental  = models.BooleanField(default=False)
    Plan_de_manejo_de_escombros  = models.BooleanField(default=False)
    Plan_de_manejo_de_transito  = models.BooleanField(default=False)
    Avaluó_comercial  = models.BooleanField(default=False)
    Declaración_de_antigüedad   = models.BooleanField(default=False)
    Declaración_de_no_bienes   = models.BooleanField(default=False)
    Declaración_extrajuicio_de_sana_posesión   = models.BooleanField(default=False)
    Copia_de_licencia   = models.BooleanField(default=False)
    Certificado_de_nomenclatura   = models.BooleanField(default=False)
    Certificado_del_sisben   = models.BooleanField(default=False)
    Certificado_de_desplazado   = models.BooleanField(default=False)
    Carta_de_aceptación_por_revisor   = models.BooleanField(default=False)
    Poder_autenticado   = models.BooleanField(default=False)
    Autorización_autenticada    = models.BooleanField(default=False)
    Solicitud = models.BooleanField(default=False)
    Certificado_financiero    = models.BooleanField(default=False)
    Contrato_de_promesa_de_compraventa = models.BooleanField(default=False)

    # observation = models.TextField(max_length=1000, null=True, blank=True)
    # observation_date = models.DateField(null=True, blank=True)

    # review = models.BooleanField(default=False)
    # review_date = models.DateField(null=True, blank=True)

    # underReview = models.BooleanField(default=False)
    # underReview_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.filev}"


class FileType(models.Model):
    name = models.CharField(max_length=110)

    def __str__(self):
        return self.name

class operatorObservation(models.Model):
    fileID = models.ForeignKey("File", related_name="observationList", null=True, blank=True, on_delete=models.CASCADE)
    observation = models.TextField(max_length=2000, null=True, blank=True)
    createdAt = models.DateField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.observation


class StateType(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name



class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_username(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField(max_length=30)  # New, Contacted, Converted, Unconverted
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class LoggerAll(models.Model):
    UPDATED = 'update'
    CREATE = 'create'
    DELETE = 'delete'
    EMPTY = 'empty'

    ACTION_CHOICES = (
        (UPDATED, 'update'),
        (CREATE, 'create'),
        (DELETE, 'delete'),
        (EMPTY, 'empty'),
    )

    msg = models.CharField(max_length=500)
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)
    action = models.CharField(max_length=20, choices=ACTION_CHOICES, default=EMPTY)
    createdAt = models.DateField(auto_now_add=True)

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )
        widgets = {
            'email' : forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'username' : forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'first_name' : forms.TextInput(attrs={
                'class': 'form-control'
            }),
            'last_name' : forms.TextInput(attrs={
                'class': 'form-control'
            }),
        }

class RemoveUser(forms.Form):
    username = forms.CharField()

agents/api/views.py
from rest_framework import generics
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from .serializers import AgentSignUpSerializer
from account.models import User, UserProfile
from filed.models import Agent

from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.http import urlsafe_base64_decode
from django.template.loader import render_to_string
from django.conf import settings
from agents.tokens import account_activation_token
from rest_framework.views import APIView
from rest_framework import status

class CreateAgentView(generics.GenericAPIView):
    serializer_class = AgentSignUpSerializer
    def post(self, request, *args, **kwargs):
        serializer=self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.save()

        if user.is_support == True:
            UserProfile.objects.create(user=user)
        if user.is_agent == True:
            Agent.objects.create(
            user=user,
            organisation= self.request.user.userprofile
        )

        # ====== send email notification ===== #
        email = user.email
        subject= 'Activate Your SLDC Account'
        from_email= settings.EMAIL_HOST_USER
        html_template = 'account/account_activation_email.html'

        html_message = render_to_string(html_template, {
                'user': user,
                'domain': 'licenciasurbanisticas.com',
                # 'domain': '127.0.0.1:3000',
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })

        message = EmailMessage(subject, html_message, from_email, [email])
        message.content_subtype = 'html' # this is required because there is no plain text email version
        message.send()

        return Response({
            "user": AgentSignUpSerializer(user, context=self.get_serializer_context()).data,
            "message": "account create successfully"
        })


class ActivateView(APIView):
    def post(self, request, uidb64, token):

        uid = force_bytes(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)

        try:
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            
# <<<<<<< HEAD
            return Response({
                "message": "Your account has been activated successfully"
                })
# =======
            return Response("Your account has been activated now")
# >>>>>>> 41d075ff9767a8928ee7b24f76954159388e6cc1
        else:
            return Response("Oops! something is wrong")

templates/agents/agent_create.html
{% extends "layout.html" %}

{% block content %}

<div class="">
        <a class="text-dark btn shadow-sm mt-2" style="text-decoration: none;" href="{% url 'agents:agent-list' %}">Go back to agents</a>
</div>

<section class="d-flex align-items-center my-4 justify-content-center" style="height: 100%;">
    <div class="rounded shadow" style="width: 360px; height: min-content; padding: 20px; ">
    
        <h1 class="text-center fs-3 mb-2">Create a new agent!</h1>
        
        {% if form.errors %}
            <div class="alert alert-danger">
                {{ form.errors }}
            </div>
        {% endif %}

        <form method="post" class="needs-validation">
            {% csrf_token %}
            <div class="form-group was-validated">
                <label class="form-label" for="email">Email address</label>
                {{form.email}}
                <!-- <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">  -->

                <div class="invalid-feedback">
                    Please enter your email address
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="Username">Username</label>
                {{form.username}}
                <!-- <input type="text" name="username" maxlength="150" class="form-control" required id="id_username">  -->
                <div class="invalid-feedback">
                    Please enter your Username
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="First name">First name</label>
                {{form.first_name}}
                <!-- <input type="text" name="first_name" maxlength="150" class="form-control" required id="id_first_name">  -->
                <div class="invalid-feedback">
                    Please enter your first_name
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="First name">Last name</label>
                {{form.last_name}}
                <!-- <input type="text" name="last_name" maxlength="150" class="form-control" required id="id_last_name">  -->
                <div class="invalid-feedback">
                    Please enter your first_name
                </div>
            </div>
            <input class="btn btn-success w-100 mt-3" type="submit" value="Submit">
        </form>

        <!-- {{form}} -->
    
    </div>
</section>
{% endblock content %}

templates/agents/agent_delete.html
{% extends "layout.html" %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'agents:agent-list' %}">Go back to agents</a>
    </div>
    <h1 class="text-3xl text-gray-800">Are you sure you want to delete this agent?</h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
    <div class="py-5 mt-5">
        <a class="hover:text-blue-500" href="{% url 'agents:agent-detail' object.pk %}">Cancel</a>
    </div>
</div>
{% endblock content %}

templates/agents/agent_detail.html
{% extends "layout.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>    
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Full Name</span>
                <span class="ml-auto text-gray-900">{{ agent.user.first_name }} {{ agent.user.last_name }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Email</span>
                <span class="ml-auto text-gray-900">{{ agent.user.email }}</span>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/agents/agent_list.html
{% extends "layout.html" %}

{% block content %}
<h1 class="text-center">Agents</h1>
    <div class="d-flex justify-content-around align-items-center py-3 mt-5">
        <div>
            <a class="btn shadow-sm" style="text-decoration: none;" href="{% url 'agents:support-create' %}">Create a new support</a>
        </div>
        <div>
            <a class="btn shadow-sm" style="text-decoration: none;" href="{% url 'agents:agent-create' %}">Create a new agent</a>
        </div>
    </div>


    <div class="row">
        <div class="col-md-12 my-3">
        <div class="card">
            <div class="card-header">
            <span><i class="bi bi-table me-2"></i></span> Data Table
            </div>
            <div class="card-body">
            <div class="table-responsive">
                <table
                id="example"
                class="table data-table"
                style="width: 100%"
                >
                <thead class="bg-light">
                    <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Action</th>
                    </tr>
                </thead>
                    <tbody>
                    {% for agent in object_list %}
                        <tr class="bg-white">
                            <td>
                                {{ agent.user.username }}
                            </td>
                            <td>
                                {{ agent.user.email }}
                            </td>
                            <td>
                                {% if agent.user.is_agent %}    
                                    <!-- Agent -->
                                    responsable
                                {% else %}
                                    <!-- Support -->
                                    Atención al cliente
                                {% endif %}
                            </td>
                            <td>

                                <a href="{% url 'agents:agent-update' agent.pk %}"><i class="material-icons text-warning" data-toggle="tooltip" title="Edit">&#xE254;</i></a>
                                <!-- <a href="#"><i class="material-icons" title="View" data-toggle="tooltip">&#xE417;</i></a> -->
                                <a data-bs-toggle="modal" href="#deleteEmployeeModal" class="text-danger"><i class="material-icons" data-toggle="tooltip" title="Delete">&#xE872;</i></a>
                            
                            </td>

                        </tr>

                        <!-- Delete Modal -->
                        <div class="modal fade" id="deleteEmployeeModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Delete User</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body text-center">
                                    <p>Are you sure you want to delete these User?</p>
                                    <p class="text-warning"><small>This action cannot be undone.</small></p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                                    <a href="{% url 'agents:agent-delete' agent.user.id %}" class="btn btn-danger">Delete</a>
                                </div>
                                </div>
                            </div>
                        </div>

                    {% empty %}

                        <tr>
                            <td colspan="4" class="text-center">
                                <!-- There are currently no agents -->
                                Actualmente no hay responsable
                            </td>
                        </tr>

                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Action</th>
                    </tr>
                </tfoot>
                </table>
            </div>
            </div>
        </div>
        </div>
    </div>
{% endblock content %}

templates/agents/agent_update.html
{% extends "layout.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'agents:agent-delete' agent.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/agents/support_create.html
{% extends "layout.html" %}

{% block content %}

<div class="">
        <a class="" href="{% url 'agents:agent-list' %}">Go back to agents</a>
</div>

<section class="d-flex align-items-center my-4 justify-content-center" style="height: 100%;">
    <div class="rounded shadow" style="width: 360px; height: min-content; padding: 20px; ">
    
        <h1 class="text-center fs-3 mb-2">Create a new support!</h1>
        
        {% if form.errors %}
            <div class="alert alert-danger">
                {{ form.errors }}
            </div>
        {% endif %}
        
        <form method="post" class="needs-validation">
            {% csrf_token %}
            <div class="form-group was-validated">
                <label class="form-label" for="email">Email address</label>
                {{form.email}}
                <!-- <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">  -->

                <div class="invalid-feedback">
                    Please enter your email address
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="Username">Username</label>
                {{form.username}}
                <!-- <input type="text" name="username" maxlength="150" class="form-control" required id="id_username">  -->
                <div class="invalid-feedback">
                    Please enter your Username
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="First name">First name</label>
                {{form.first_name}}
                <!-- <input type="text" name="first_name" maxlength="150" class="form-control" required id="id_first_name">  -->
                <div class="invalid-feedback">
                    Please enter your first_name
                </div>
            </div>
            <div class="form-group was-validated">
                <label class="form-label" for="First name">Last name</label>
                {{form.last_name}}
                <!-- <input type="text" name="last_name" maxlength="150" class="form-control" required id="id_last_name">  -->
                <div class="invalid-feedback">
                    Please enter your first_name
                </div>
            </div>
            <input class="btn btn-success w-100 mt-3" type="submit" value="Submit">
        </form>
    
    </div>
</section>
{% endblock content %}